sonar.host.url=https://sonarcloud.io
sonar.projectKey=codeheadsystems_passkeys-browser
sonar.organization=codeheadsystems
sonar.projectName=pk-auth Browser SDK
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
